### ISSUE TITLE
Change file upload to handle .tree files

### ISSUE THREAD

**Issue by jenrogers1207** [multinet-app/multinet-girder#40]
Some of the files we have are .tree files. So far, the only non csv files we are accounting for in the file upload is newick. Though these are similar, I do not know yet how similar and if the fix for this will be adding the file edition or accounting for that in tree parsing. 

**The gist for the file is here**:
[Tree Format File](https://gist.github.com/jenrogers1207/bde230d53abf4e8b486541bbe1db7008)

**Comment by waxlamp** [comment]
Do you have an example of a .tree file we can point to from this issue?

**Comment by jenrogers1207** [comment]
> Do you have an example of a .tree file we can point to from this issue?

Yes! I am looking over a tree file that I am using as part of a sample dataset. I believe the .tree file contains branch information as well as additional attributes. I can send it to you?

**Comment by jenrogers1207** [comment]
extension for .tree added
